version: '3'

services:
  blog_postgresql:
    image: postgres:12
    container_name: blog_postgre
    volumes: 
      - postgres:/var/lib/postgresql/data  
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    networks:
      - blog_network
       
volumes:
  postgres:
    external: true
networks:
  blog_network:
    external: true